/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemamedico;

import conexion.Conexion;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.Pair;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;
import org.cs3.prolog.connector.process.PrologProcessException;

/**
 *
 * @author kronoz
 */
public class Diagnostico extends javax.swing.JFrame {

    private static ArrayList<String[]> Condiciones = new ArrayList<String[]>();
private static ArrayList<String[]> Analisis = new ArrayList<String[]>();
    /**
     * Creates new form Diagnostico
     */
    public Diagnostico() {
        initComponents();
    }

    public static void addColoracion(String a, String b) {
        String[] coloracion = new String[3];
        coloracion[0] = "coloracion";
        coloracion[1] = a;
        coloracion[2] = b;
        Condiciones.add(coloracion);
    }

    public static void addsinto(String[] retorno) {

        //lugar, Parte.getSelectedValue(), Tipo.getSelectedValue(), jSlider1.getValue()
        String[] sintoma={retorno[1],retorno[0]};
        ((DefaultTableModel)tbl_sintomas.getModel()).addRow(sintoma);
       Condiciones.add(retorno);

        }
       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Human_body_front = new javax.swing.JPanel();
        cabeza_front = new javax.swing.JLabel();
        brazo_der = new javax.swing.JLabel();
        brazo_izq = new javax.swing.JLabel();
        corazon = new javax.swing.JLabel();
        estomago = new javax.swing.JLabel();
        pantorrilla_izq = new javax.swing.JLabel();
        pecho = new javax.swing.JLabel();
        pie_der = new javax.swing.JLabel();
        pie_izq = new javax.swing.JLabel();
        pierna_der = new javax.swing.JLabel();
        pierna_izq = new javax.swing.JLabel();
        testiculos = new javax.swing.JLabel();
        body = new javax.swing.JLabel();
        Human_body_back = new javax.swing.JPanel();
        cabeza_front1 = new javax.swing.JLabel();
        brazo_der1 = new javax.swing.JLabel();
        brazo_izq1 = new javax.swing.JLabel();
        corazon1 = new javax.swing.JLabel();
        estomago1 = new javax.swing.JLabel();
        pantorrilla_izq1 = new javax.swing.JLabel();
        pecho1 = new javax.swing.JLabel();
        pie_der1 = new javax.swing.JLabel();
        pie_izq1 = new javax.swing.JLabel();
        pierna_der1 = new javax.swing.JLabel();
        pierna_izq1 = new javax.swing.JLabel();
        testiculos1 = new javax.swing.JLabel();
        body1 = new javax.swing.JLabel();
        Sintomas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_mareo = new javax.swing.JToggleButton();
        btn_vomito = new javax.swing.JToggleButton();
        btn_coloracion = new javax.swing.JButton();
        btn_sudoracion = new javax.swing.JToggleButton();
        btn_debilidad = new javax.swing.JToggleButton();
        btn_difresp = new javax.swing.JToggleButton();
        btn_boca_reseca = new javax.swing.JToggleButton();
        btn_tos = new javax.swing.JToggleButton();
        btn_estornudos = new javax.swing.JToggleButton();
        btn_flemas = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sintomas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_altura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_peso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_circunferencia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_temperatura = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_azucar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_dias = new javax.swing.JTextField();
        txt_cis = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Diagnositco");
        setBackground(new java.awt.Color(254, 254, 254));
        setResizable(false);

        cabeza_front.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cabeza_frontMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cabeza_frontMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cabeza_frontMouseEntered(evt);
            }
        });

        brazo_der.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brazo_derMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brazo_derMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brazo_derMouseEntered(evt);
            }
        });

        brazo_izq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brazo_izqMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brazo_izqMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brazo_izqMouseEntered(evt);
            }
        });

        corazon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corazonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                corazonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                corazonMouseEntered(evt);
            }
        });

        estomago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estomagoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estomagoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estomagoMouseEntered(evt);
            }
        });

        pantorrilla_izq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pantorrilla_izqMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pantorrilla_izqMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pantorrilla_izqMouseEntered(evt);
            }
        });

        pecho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pechoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pechoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pechoMouseEntered(evt);
            }
        });

        pie_der.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pie_derMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pie_derMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pie_derMouseEntered(evt);
            }
        });

        pie_izq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pie_izqMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pie_izqMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pie_izqMouseEntered(evt);
            }
        });

        pierna_der.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pierna_derMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pierna_derMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pierna_derMouseEntered(evt);
            }
        });

        pierna_izq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pierna_izqMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pierna_izqMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pierna_izqMouseEntered(evt);
            }
        });

        testiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testiculosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                testiculosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                testiculosMouseEntered(evt);
            }
        });

        body.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frontal.png"))); // NOI18N
        body.setToolTipText("");

        javax.swing.GroupLayout Human_body_frontLayout = new javax.swing.GroupLayout(Human_body_front);
        Human_body_front.setLayout(Human_body_frontLayout);
        Human_body_frontLayout.setHorizontalGroup(
            Human_body_frontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Human_body_frontLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(Human_body_frontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Human_body_frontLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(cabeza_front, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Human_body_frontLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(estomago, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Human_body_frontLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(testiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Human_body_frontLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(pie_izq, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Human_body_frontLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(pierna_izq, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Human_body_frontLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(pierna_der, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Human_body_frontLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(brazo_izq, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Human_body_frontLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(pantorrilla_izq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Human_body_frontLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(pecho, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Human_body_frontLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pie_der, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(brazo_der, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Human_body_frontLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(corazon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Human_body_frontLayout.setVerticalGroup(
            Human_body_frontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Human_body_frontLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(Human_body_frontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Human_body_frontLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(cabeza_front, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(Human_body_frontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Human_body_frontLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(estomago, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Human_body_frontLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(testiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Human_body_frontLayout.createSequentialGroup()
                                .addGap(383, 383, 383)
                                .addComponent(pie_izq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Human_body_frontLayout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(pierna_izq, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Human_body_frontLayout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(pierna_der, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Human_body_frontLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(brazo_izq, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Human_body_frontLayout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(pantorrilla_izq, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Human_body_frontLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(pecho, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Human_body_frontLayout.createSequentialGroup()
                                .addGap(382, 382, 382)
                                .addComponent(pie_der, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(brazo_der, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Human_body_frontLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(corazon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        brazo_izq.getAccessibleContext().setAccessibleName("brazo_izq");

        Human_body_back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cabeza_front1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cabeza_front1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cabeza_front1MouseEntered(evt);
            }
        });
        Human_body_back.add(cabeza_front1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 21, 60, 70));

        brazo_der1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brazo_der1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brazo_der1MouseEntered(evt);
            }
        });
        Human_body_back.add(brazo_der1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 93, 60, 210));

        brazo_izq1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brazo_izq1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brazo_izq1MouseEntered(evt);
            }
        });
        Human_body_back.add(brazo_izq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 94, 60, 210));

        corazon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                corazon1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                corazon1MouseEntered(evt);
            }
        });
        Human_body_back.add(corazon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 108, 50, 70));

        estomago1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estomago1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estomago1MouseEntered(evt);
            }
        });
        Human_body_back.add(estomago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 172, 90, 80));

        pantorrilla_izq1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pantorrilla_izq1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pantorrilla_izq1MouseEntered(evt);
            }
        });
        Human_body_back.add(pantorrilla_izq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 370, 40, 110));

        pecho1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pecho1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pecho1MouseEntered(evt);
            }
        });
        Human_body_back.add(pecho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 120, 90, 70));

        pie_der1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pie_der1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pie_der1MouseEntered(evt);
            }
        });
        Human_body_back.add(pie_der1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 475, 60, 30));

        pie_izq1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pie_izq1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pie_izq1MouseEntered(evt);
            }
        });
        Human_body_back.add(pie_izq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 476, 60, 30));

        pierna_der1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pierna_der1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pierna_der1MouseEntered(evt);
            }
        });
        Human_body_back.add(pierna_der1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 280, 60, 110));

        pierna_izq1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pierna_izq1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pierna_izq1MouseEntered(evt);
            }
        });
        Human_body_back.add(pierna_izq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 290, 50, 90));

        testiculos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                testiculos1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                testiculos1MouseEntered(evt);
            }
        });
        Human_body_back.add(testiculos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 242, 110, 50));

        body1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trasero.png"))); // NOI18N
        body1.setToolTipText("");
        Human_body_back.add(body1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 12, 190, 506));

        Sintomas.setBorder(javax.swing.BorderFactory.createTitledBorder("Sintomas"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Añadir Sintomas"));

        btn_mareo.setText("Mareo");
        btn_mareo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btn_mareoStateChanged(evt);
            }
        });
        btn_mareo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mareoActionPerformed(evt);
            }
        });

        btn_vomito.setText("Vomito");
        btn_vomito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vomitoActionPerformed(evt);
            }
        });

        btn_coloracion.setText("Coloracion");
        btn_coloracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_coloracionActionPerformed(evt);
            }
        });

        btn_sudoracion.setText("Sudoracion");
        btn_sudoracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sudoracionActionPerformed(evt);
            }
        });

        btn_debilidad.setText("Debilidad");
        btn_debilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_debilidadActionPerformed(evt);
            }
        });

        btn_difresp.setText("Dificultad de Respirar");
        btn_difresp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_difrespActionPerformed(evt);
            }
        });

        btn_boca_reseca.setText("Boca Reseca");
        btn_boca_reseca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_boca_resecaActionPerformed(evt);
            }
        });

        btn_tos.setText("Tos");
        btn_tos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tosActionPerformed(evt);
            }
        });

        btn_estornudos.setText("Estornudos");
        btn_estornudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estornudosActionPerformed(evt);
            }
        });

        btn_flemas.setText("Flemas");
        btn_flemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_flemasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_mareo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_vomito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_coloracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_sudoracion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_debilidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_difresp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_boca_reseca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_tos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_estornudos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_flemas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mareo)
                    .addComponent(btn_vomito)
                    .addComponent(btn_coloracion)
                    .addComponent(btn_sudoracion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_debilidad)
                    .addComponent(btn_difresp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_boca_reseca)
                    .addComponent(btn_tos)
                    .addComponent(btn_estornudos)
                    .addComponent(btn_flemas)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lista de Sintomas"));

        tbl_sintomas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sintoma", "Parte del Cuerpo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_sintomas);

        jButton1.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout SintomasLayout = new javax.swing.GroupLayout(Sintomas);
        Sintomas.setLayout(SintomasLayout);
        SintomasLayout.setHorizontalGroup(
            SintomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SintomasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SintomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SintomasLayout.setVerticalGroup(
            SintomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SintomasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos"));

        jLabel1.setText("Talla:");

        txt_altura.setText("172");
        txt_altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alturaActionPerformed(evt);
            }
        });

        jLabel2.setText("cms");

        jLabel3.setText("Peso:");

        txt_peso.setText("75");

        jLabel4.setText("kgs");

        jLabel5.setText("Edad:");

        jLabel6.setText("años");

        txt_edad.setText("70");

        jLabel7.setText("Crc. Adb.");

        txt_circunferencia.setText("70");

        jLabel8.setText("cms");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_peso)))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_circunferencia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(txt_circunferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(0, 48, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Mediciones"));

        jLabel9.setText("Temperatura:");

        txt_temperatura.setText("70");

        jLabel10.setText("C°");

        jLabel11.setText("Azucar:");

        txt_azucar.setText("70");

        jLabel12.setText("mg/mm");

        jLabel13.setText("Presion:");

        txt_dias.setText("160");
        txt_dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diasActionPerformed(evt);
            }
        });

        txt_cis.setText("80");

        jLabel14.setText("/");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_temperatura, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(txt_azucar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txt_dias, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cis, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_azucar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Evaluacion"));

        jButton3.setText("Analizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Human_body_front, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Human_body_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Sintomas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Human_body_front, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sintomas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Human_body_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cabeza_frontMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabeza_frontMouseEntered

        setPart(cabeza_front, "cabeza_front");

    }//GEN-LAST:event_cabeza_frontMouseEntered

    private void cabeza_frontMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabeza_frontMouseExited
        reset(cabeza_front);        // TODO add your handling code here:
    }//GEN-LAST:event_cabeza_frontMouseExited

    private void brazo_derMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazo_derMouseEntered
        setPart(brazo_der, "brazo_der_front");      // TODO add your handling code here:
    }//GEN-LAST:event_brazo_derMouseEntered

    private void brazo_izqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazo_izqMouseEntered
        setPart(brazo_izq, "brazo_izq_front");
    }//GEN-LAST:event_brazo_izqMouseEntered

    private void corazonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corazonMouseEntered

        setPart(corazon, "corazon_frontal");          // TODO add your handling code here:
    }//GEN-LAST:event_corazonMouseEntered

    private void estomagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estomagoMouseEntered
        setPart(estomago, "estomago_front");        // TODO add your handling code here:
    }//GEN-LAST:event_estomagoMouseEntered

    private void pantorrilla_izqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pantorrilla_izqMouseEntered
        setPart(pantorrilla_izq, "pantorrilla_izq_front");        // TODO add your handling code here:
    }//GEN-LAST:event_pantorrilla_izqMouseEntered

    private void pechoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pechoMouseEntered
        setPart(pecho, "pecho_front");        // TODO add your handling code here:
    }//GEN-LAST:event_pechoMouseEntered

    private void pie_derMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pie_derMouseEntered
        setPart(pie_der, "pie_der_front");        // TODO add your handling code here:
    }//GEN-LAST:event_pie_derMouseEntered

    private void pie_izqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pie_izqMouseEntered
        setPart(pie_izq, "pie_izq_front");        // TODO add your handling code here:
    }//GEN-LAST:event_pie_izqMouseEntered

    private void pierna_derMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pierna_derMouseEntered
        setPart(pierna_der, "pierna_der_front");        // TODO add your handling code here:
    }//GEN-LAST:event_pierna_derMouseEntered

    private void pierna_izqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pierna_izqMouseEntered
        setPart(pierna_izq, "pierna_izq_front");        // TODO add your handling code here:
    }//GEN-LAST:event_pierna_izqMouseEntered

    private void testiculosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testiculosMouseEntered
        setPart(testiculos, "testiculos_front");        // TODO add your handling code here:
    }//GEN-LAST:event_testiculosMouseEntered

    private void brazo_derMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazo_derMouseExited
        reset((JLabel) evt.getComponent());        // TODO add your handling code here:
    }//GEN-LAST:event_brazo_derMouseExited

    private void brazo_izqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazo_izqMouseExited
        reset((JLabel) evt.getComponent());         // TODO add your handling code here:
    }//GEN-LAST:event_brazo_izqMouseExited

    private void corazonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corazonMouseExited
        reset((JLabel) evt.getComponent());         // TODO add your handling code here:
    }//GEN-LAST:event_corazonMouseExited

    private void estomagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estomagoMouseExited
        reset((JLabel) evt.getComponent());         // TODO add your handling code here:
    }//GEN-LAST:event_estomagoMouseExited

    private void pantorrilla_izqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pantorrilla_izqMouseExited
        reset((JLabel) evt.getComponent());         // TODO add your handling code here:
    }//GEN-LAST:event_pantorrilla_izqMouseExited

    private void pechoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pechoMouseExited
        reset((JLabel) evt.getComponent());         // TODO add your handling code here:
    }//GEN-LAST:event_pechoMouseExited

    private void pie_derMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pie_derMouseExited
        reset((JLabel) evt.getComponent());         // TODO add your handling code here:
    }//GEN-LAST:event_pie_derMouseExited

    private void pie_izqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pie_izqMouseExited
        reset((JLabel) evt.getComponent());         // TODO add your handling code here:
    }//GEN-LAST:event_pie_izqMouseExited

    private void pierna_derMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pierna_derMouseExited
        reset((JLabel) evt.getComponent());         // TODO add your handling code here:
    }//GEN-LAST:event_pierna_derMouseExited

    private void pierna_izqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pierna_izqMouseExited
        reset((JLabel) evt.getComponent());         // TODO add your handling code here:
    }//GEN-LAST:event_pierna_izqMouseExited

    private void testiculosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testiculosMouseExited
        reset((JLabel) evt.getComponent());         // TODO add your handling code here:
    }//GEN-LAST:event_testiculosMouseExited

    private void cabeza_front1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabeza_front1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cabeza_front1MouseExited

    private void cabeza_front1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabeza_front1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cabeza_front1MouseEntered

    private void brazo_der1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazo_der1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_brazo_der1MouseExited

    private void brazo_der1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazo_der1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_brazo_der1MouseEntered

    private void brazo_izq1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazo_izq1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_brazo_izq1MouseExited

    private void brazo_izq1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazo_izq1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_brazo_izq1MouseEntered

    private void corazon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corazon1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_corazon1MouseExited

    private void corazon1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corazon1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_corazon1MouseEntered

    private void estomago1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estomago1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_estomago1MouseExited

    private void estomago1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estomago1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_estomago1MouseEntered

    private void pantorrilla_izq1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pantorrilla_izq1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pantorrilla_izq1MouseExited

    private void pantorrilla_izq1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pantorrilla_izq1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pantorrilla_izq1MouseEntered

    private void pecho1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pecho1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pecho1MouseExited

    private void pecho1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pecho1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pecho1MouseEntered

    private void pie_der1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pie_der1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pie_der1MouseExited

    private void pie_der1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pie_der1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pie_der1MouseEntered

    private void pie_izq1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pie_izq1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pie_izq1MouseExited

    private void pie_izq1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pie_izq1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pie_izq1MouseEntered

    private void pierna_der1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pierna_der1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pierna_der1MouseExited

    private void pierna_der1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pierna_der1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pierna_der1MouseEntered

    private void pierna_izq1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pierna_izq1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pierna_izq1MouseExited

    private void pierna_izq1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pierna_izq1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pierna_izq1MouseEntered

    private void testiculos1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testiculos1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_testiculos1MouseExited

    private void testiculos1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testiculos1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_testiculos1MouseEntered

    private void btn_mareoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mareoActionPerformed

        addElement(btn_mareo, "sintoma", "mareo");
    }//GEN-LAST:event_btn_mareoActionPerformed

    private void btn_vomitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vomitoActionPerformed
        addElement(btn_vomito, "sintoma", "vomito");        // TODO add your handling code here:
    }//GEN-LAST:event_btn_vomitoActionPerformed

    private void btn_coloracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_coloracionActionPerformed
        Coloracion v = new Coloracion((DefaultTableModel) tbl_sintomas.getModel());
        v.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_coloracionActionPerformed

    private void btn_sudoracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sudoracionActionPerformed
        addElement(btn_sudoracion, "sintoma", "sudoracion");        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sudoracionActionPerformed

    private void btn_debilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_debilidadActionPerformed
        addElement(btn_debilidad, "sintoma", "debilidad");        // TODO add your handling code here:
    }//GEN-LAST:event_btn_debilidadActionPerformed

    private void btn_difrespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_difrespActionPerformed
        addElement(btn_difresp, "sintoma", "dificultad_respirar");        // TODO add your handling code here:
    }//GEN-LAST:event_btn_difrespActionPerformed

    private void btn_boca_resecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_boca_resecaActionPerformed
        addElement(btn_boca_reseca, "sintoma", "boca_reseca");        // TODO add your handling code here:
    }//GEN-LAST:event_btn_boca_resecaActionPerformed

    private void btn_tosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tosActionPerformed
        addElement(btn_tos, "sintoma", "tos");        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tosActionPerformed

    private void btn_estornudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estornudosActionPerformed
        addElement(btn_estornudos, "sintoma", "estornudos");        // TODO add your handling code here:
    }//GEN-LAST:event_btn_estornudosActionPerformed

    private void btn_flemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_flemasActionPerformed
        addElement(btn_flemas, "sintoma", "flemas");        // TODO add your handling code here:
    }//GEN-LAST:event_btn_flemasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            Conexion c = new Conexion();
            
            
            String[] t ={"temperatura", txt_temperatura.getText()};
            String[] pr ={"presion", txt_dias.getText() + "," + txt_cis.getText()};
            String[] a ={"altura", txt_altura.getText()};
            String[] p ={"peso", txt_peso.getText()};
            String[] az ={"nivel_azucar", txt_azucar.getText()};
            String[] e ={"edad", txt_edad.getText()};
            String[] ci ={"circunferencia", txt_circunferencia.getText()};
            String[] imc ={"imc",String.valueOf(Float.parseFloat(txt_peso.getText()) / (Math.pow(Double.parseDouble(txt_altura.getText()) / 100, 2)))};
            
      
            Analisis.add(t);
            Analisis.add(a);
            Analisis.add(p);
            Analisis.add(az);
            Analisis.add(e);
            Analisis.add(ci);
            Analisis.add(pr);
            Analisis.add(imc);
            c.addAnalisis(Analisis);
            c.addCondicion(Condiciones);
            ArrayList<String> enf = c.getEnfermedad();
            for (String i : enf) {
                System.out.println(i);
            }
            ArrayList<String> con = c.getCondicion();
            for (String i : con) {
                System.out.println(i);
            }

        } catch (IOException ex) {
            Logger.getLogger(Diagnostico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PrologProcessException ex) {
            Logger.getLogger(Diagnostico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_mareoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btn_mareoStateChanged

    }//GEN-LAST:event_btn_mareoStateChanged

    private void cabeza_frontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabeza_frontMouseClicked
        Sintoma s = new Sintoma("cabeza");
        s.setVisible(true);
    }//GEN-LAST:event_cabeza_frontMouseClicked

    private void brazo_derMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazo_derMouseClicked
        Sintoma s = new Sintoma("brazo_der");
        s.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_brazo_derMouseClicked

    private void brazo_izqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazo_izqMouseClicked
        Sintoma s = new Sintoma("brazo_izq");
        s.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_brazo_izqMouseClicked

    private void corazonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corazonMouseClicked
        Sintoma s = new Sintoma("corazon");
        s.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_corazonMouseClicked

    private void estomagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estomagoMouseClicked
        Sintoma s = new Sintoma("abdomen");
        s.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_estomagoMouseClicked

    private void pantorrilla_izqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pantorrilla_izqMouseClicked
        Sintoma s = new Sintoma("pantorrilla");
        s.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_pantorrilla_izqMouseClicked

    private void pechoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pechoMouseClicked
        Sintoma s = new Sintoma("pecho");
        s.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_pechoMouseClicked

    private void pie_derMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pie_derMouseClicked
        Sintoma s = new Sintoma("pie_der");
        s.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_pie_derMouseClicked

    private void pie_izqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pie_izqMouseClicked
        Sintoma s = new Sintoma("pie_izq");
        s.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_pie_izqMouseClicked

    private void pierna_derMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pierna_derMouseClicked
        Sintoma s = new Sintoma("pierna_der");
        s.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_pierna_derMouseClicked

    private void pierna_izqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pierna_izqMouseClicked
        Sintoma s = new Sintoma("pierna_izq");
        s.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_pierna_izqMouseClicked

    private void testiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testiculosMouseClicked
        Sintoma s = new Sintoma("testiculos");
        s.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_testiculosMouseClicked

    private void txt_alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alturaActionPerformed

    private void txt_diasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diasActionPerformed

    private void addElement(JToggleButton a, String b, String c) {

        DefaultTableModel x = (DefaultTableModel) tbl_sintomas.getModel();
        if (a.isSelected()) {

            Analisis.add(new String[]{b,c});
            String[] elemento = {b, c};
            x.addRow(elemento);

        } else {
            Analisis.remove(new String[]{b, c});
            for (int i = 0; i < x.getRowCount(); i++) {
                if (tbl_sintomas.getValueAt(i, 0) == b && tbl_sintomas.getValueAt(i, 1) == c) {
                    x.removeRow(i);
                }
            }
        }

    }

    private void reset(JLabel label) {
        label.setIcon(null);
    }

    private void setPart(JLabel label, String imagen) {

        ImageIcon ima = new ImageIcon("src/img/" + imagen + ".png");
        Icon ico = (Icon) ima;
        label.setIcon(ico);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnostico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Human_body_back;
    private javax.swing.JPanel Human_body_front;
    private javax.swing.JPanel Sintomas;
    private javax.swing.JLabel body;
    private javax.swing.JLabel body1;
    private javax.swing.JLabel brazo_der;
    private javax.swing.JLabel brazo_der1;
    private javax.swing.JLabel brazo_izq;
    private javax.swing.JLabel brazo_izq1;
    private javax.swing.JToggleButton btn_boca_reseca;
    private javax.swing.JButton btn_coloracion;
    private javax.swing.JToggleButton btn_debilidad;
    private javax.swing.JToggleButton btn_difresp;
    private javax.swing.JToggleButton btn_estornudos;
    private javax.swing.JToggleButton btn_flemas;
    private javax.swing.JToggleButton btn_mareo;
    private javax.swing.JToggleButton btn_sudoracion;
    private javax.swing.JToggleButton btn_tos;
    private javax.swing.JToggleButton btn_vomito;
    private javax.swing.JLabel cabeza_front;
    private javax.swing.JLabel cabeza_front1;
    private javax.swing.JLabel corazon;
    private javax.swing.JLabel corazon1;
    private javax.swing.JLabel estomago;
    private javax.swing.JLabel estomago1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel pantorrilla_izq;
    private javax.swing.JLabel pantorrilla_izq1;
    private javax.swing.JLabel pecho;
    private javax.swing.JLabel pecho1;
    private javax.swing.JLabel pie_der;
    private javax.swing.JLabel pie_der1;
    private javax.swing.JLabel pie_izq;
    private javax.swing.JLabel pie_izq1;
    private javax.swing.JLabel pierna_der;
    private javax.swing.JLabel pierna_der1;
    private javax.swing.JLabel pierna_izq;
    private javax.swing.JLabel pierna_izq1;
    public static javax.swing.JTable tbl_sintomas;
    private javax.swing.JLabel testiculos;
    private javax.swing.JLabel testiculos1;
    private javax.swing.JTextField txt_altura;
    private javax.swing.JTextField txt_azucar;
    private javax.swing.JTextField txt_circunferencia;
    private javax.swing.JTextField txt_cis;
    private javax.swing.JTextField txt_dias;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_peso;
    private javax.swing.JTextField txt_temperatura;
    // End of variables declaration//GEN-END:variables
}
